// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fraq.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_fraq_options
int rcpp_fraq_options(const std::string& option, const int value, const bool set);
RcppExport SEXP _fraq_rcpp_fraq_options(SEXP optionSEXP, SEXP valueSEXP, SEXP setSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::string& >::type option(optionSEXP);
    Rcpp::traits::input_parameter< const int >::type value(valueSEXP);
    Rcpp::traits::input_parameter< const bool >::type set(setSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fraq_options(option, value, set));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fraq_downsample
void rcpp_fraq_downsample(std::vector<std::string> input, const std::vector<std::string>& output, const double amount, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_downsample(SEXP inputSEXP, SEXP outputSEXP, SEXP amountSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const double >::type amount(amountSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_downsample(input, output, amount, nthreads);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_slice
void rcpp_fraq_slice(std::vector<std::string> input, const std::vector<std::string>& output, const size_t limit, const std::vector<size_t>& select, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_slice(SEXP inputSEXP, SEXP outputSEXP, SEXP limitSEXP, SEXP selectSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const size_t >::type limit(limitSEXP);
    Rcpp::traits::input_parameter< const std::vector<size_t>& >::type select(selectSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_slice(input, output, limit, select, nthreads);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_convert
void rcpp_fraq_convert(std::vector<std::string> input, const std::vector<std::string>& output, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_convert(SEXP inputSEXP, SEXP outputSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_convert(input, output, nthreads);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_run_r
void rcpp_fraq_run_r(std::vector<std::string> input, Rcpp::Function kernel, const size_t limit, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_run_r(SEXP inputSEXP, SEXP kernelSEXP, SEXP limitSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const size_t >::type limit(limitSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_run_r(input, kernel, limit, nthreads);
    return R_NilValue;
END_RCPP
}
// loaded_in_fork_child
void loaded_in_fork_child(const bool value);
RcppExport SEXP _fraq_loaded_in_fork_child(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< const bool >::type value(valueSEXP);
    loaded_in_fork_child(value);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_chunk
void rcpp_fraq_chunk(std::vector<std::string> input, const std::vector<std::string>& output_prefix, const std::string& output_suffix, const double chunk_size, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_chunk(SEXP inputSEXP, SEXP output_prefixSEXP, SEXP output_suffixSEXP, SEXP chunk_sizeSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output_prefix(output_prefixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_suffix(output_suffixSEXP);
    Rcpp::traits::input_parameter< const double >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_chunk(input, output_prefix, output_suffix, chunk_size, nthreads);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_concat
void rcpp_fraq_concat(const std::vector<std::string>& input, const std::string& output, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_concat(SEXP inputSEXP, SEXP outputSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_concat(input, output, nthreads);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_count_barcodes
DataFrame rcpp_fraq_count_barcodes(const std::vector<std::string>& input, const std::vector<std::string>& barcodes, const int max_distance, const bool allow_revcomp, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_count_barcodes(SEXP inputSEXP, SEXP barcodesSEXP, SEXP max_distanceSEXP, SEXP allow_revcompSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< const bool >::type allow_revcomp(allow_revcompSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fraq_count_barcodes(input, barcodes, max_distance, allow_revcomp, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fraq_demux
void rcpp_fraq_demux(const std::vector<std::string>& input, const std::vector<std::string>& output_format, const std::vector<std::string>& barcodes, const int max_distance, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_demux(SEXP inputSEXP, SEXP output_formatSEXP, SEXP barcodesSEXP, SEXP max_distanceSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output_format(output_formatSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_demux(input, output_format, barcodes, max_distance, nthreads);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_quality_filter
void rcpp_fraq_quality_filter(const std::vector<std::string>& input, const std::vector<std::string>& output, const double min_mean_quality, const int max_low_q_bases, const int low_q_threshold, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_quality_filter(SEXP inputSEXP, SEXP outputSEXP, SEXP min_mean_qualitySEXP, SEXP max_low_q_basesSEXP, SEXP low_q_thresholdSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const double >::type min_mean_quality(min_mean_qualitySEXP);
    Rcpp::traits::input_parameter< const int >::type max_low_q_bases(max_low_q_basesSEXP);
    Rcpp::traits::input_parameter< const int >::type low_q_threshold(low_q_thresholdSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_quality_filter(input, output, min_mean_quality, max_low_q_bases, low_q_threshold, nthreads);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_merge_pairs
Rcpp::List rcpp_fraq_merge_pairs(const std::vector<std::string>& input, const std::string& output_merged, const std::vector<std::string>& output_unmerged, const int min_overlap, const double max_mismatch_rate, const std::string& consensus_mode, const bool trim_overhang, const bool revcomp_R2, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_merge_pairs(SEXP inputSEXP, SEXP output_mergedSEXP, SEXP output_unmergedSEXP, SEXP min_overlapSEXP, SEXP max_mismatch_rateSEXP, SEXP consensus_modeSEXP, SEXP trim_overhangSEXP, SEXP revcomp_R2SEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_merged(output_mergedSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output_unmerged(output_unmergedSEXP);
    Rcpp::traits::input_parameter< const int >::type min_overlap(min_overlapSEXP);
    Rcpp::traits::input_parameter< const double >::type max_mismatch_rate(max_mismatch_rateSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type consensus_mode(consensus_modeSEXP);
    Rcpp::traits::input_parameter< const bool >::type trim_overhang(trim_overhangSEXP);
    Rcpp::traits::input_parameter< const bool >::type revcomp_R2(revcomp_R2SEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fraq_merge_pairs(input, output_merged, output_unmerged, min_overlap, max_mismatch_rate, consensus_mode, trim_overhang, revcomp_R2, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fraq_trim_adapters
DataFrame rcpp_fraq_trim_adapters(const std::vector<std::string>& input, const std::vector<std::string>& output, const std::vector<std::string>& adapters, const int max_distance, const bool filter_untrimmed, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_trim_adapters(SEXP inputSEXP, SEXP outputSEXP, SEXP adaptersSEXP, SEXP max_distanceSEXP, SEXP filter_untrimmedSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< const int >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< const bool >::type filter_untrimmed(filter_untrimmedSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fraq_trim_adapters(input, output, adapters, max_distance, filter_untrimmed, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fraq_summary
Rcpp::List rcpp_fraq_summary(const std::vector<std::string>& input, const bool phred33, const int min_overlap, const double max_mismatch_rate, const size_t limit, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_summary(SEXP inputSEXP, SEXP phred33SEXP, SEXP min_overlapSEXP, SEXP max_mismatch_rateSEXP, SEXP limitSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const bool >::type phred33(phred33SEXP);
    Rcpp::traits::input_parameter< const int >::type min_overlap(min_overlapSEXP);
    Rcpp::traits::input_parameter< const double >::type max_mismatch_rate(max_mismatch_rateSEXP);
    Rcpp::traits::input_parameter< const size_t >::type limit(limitSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fraq_summary(input, phred33, min_overlap, max_mismatch_rate, limit, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fraq_align
DataFrame rcpp_fraq_align(CharacterVector query, CharacterVector target, int max_distance, std::string ambiguity_base, std::string boundary, std::string distance_metric);
RcppExport SEXP _fraq_rcpp_fraq_align(SEXP querySEXP, SEXP targetSEXP, SEXP max_distanceSEXP, SEXP ambiguity_baseSEXP, SEXP boundarySEXP, SEXP distance_metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< std::string >::type ambiguity_base(ambiguity_baseSEXP);
    Rcpp::traits::input_parameter< std::string >::type boundary(boundarySEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_metric(distance_metricSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fraq_align(query, target, max_distance, ambiguity_base, boundary, distance_metric));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fraq_wait
void rcpp_fraq_wait(std::vector<std::string> input, const std::vector<std::string>& output, const int sleep_ms, const int nthreads);
RcppExport SEXP _fraq_rcpp_fraq_wait(SEXP inputSEXP, SEXP outputSEXP, SEXP sleep_msSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const int >::type sleep_ms(sleep_msSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_fraq_wait(input, output, sleep_ms, nthreads);
    return R_NilValue;
END_RCPP
}
// rcpp_fraq_mem_list
DataFrame rcpp_fraq_mem_list();
RcppExport SEXP _fraq_rcpp_fraq_mem_list() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_fraq_mem_list());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fraq_mem_remove
bool rcpp_fraq_mem_remove(const std::string& mem_key);
RcppExport SEXP _fraq_rcpp_fraq_mem_remove(SEXP mem_keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::string& >::type mem_key(mem_keySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fraq_mem_remove(mem_key));
    return rcpp_result_gen;
END_RCPP
}
// fraq_fifo_supported
bool fraq_fifo_supported();
RcppExport SEXP _fraq_fraq_fifo_supported() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(fraq_fifo_supported());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fraq_rcpp_fraq_options", (DL_FUNC) &_fraq_rcpp_fraq_options, 3},
    {"_fraq_rcpp_fraq_downsample", (DL_FUNC) &_fraq_rcpp_fraq_downsample, 4},
    {"_fraq_rcpp_fraq_slice", (DL_FUNC) &_fraq_rcpp_fraq_slice, 5},
    {"_fraq_rcpp_fraq_convert", (DL_FUNC) &_fraq_rcpp_fraq_convert, 3},
    {"_fraq_rcpp_fraq_run_r", (DL_FUNC) &_fraq_rcpp_fraq_run_r, 4},
    {"_fraq_loaded_in_fork_child", (DL_FUNC) &_fraq_loaded_in_fork_child, 1},
    {"_fraq_rcpp_fraq_chunk", (DL_FUNC) &_fraq_rcpp_fraq_chunk, 5},
    {"_fraq_rcpp_fraq_concat", (DL_FUNC) &_fraq_rcpp_fraq_concat, 3},
    {"_fraq_rcpp_fraq_count_barcodes", (DL_FUNC) &_fraq_rcpp_fraq_count_barcodes, 5},
    {"_fraq_rcpp_fraq_demux", (DL_FUNC) &_fraq_rcpp_fraq_demux, 5},
    {"_fraq_rcpp_fraq_quality_filter", (DL_FUNC) &_fraq_rcpp_fraq_quality_filter, 6},
    {"_fraq_rcpp_fraq_merge_pairs", (DL_FUNC) &_fraq_rcpp_fraq_merge_pairs, 9},
    {"_fraq_rcpp_fraq_trim_adapters", (DL_FUNC) &_fraq_rcpp_fraq_trim_adapters, 6},
    {"_fraq_rcpp_fraq_summary", (DL_FUNC) &_fraq_rcpp_fraq_summary, 6},
    {"_fraq_rcpp_fraq_align", (DL_FUNC) &_fraq_rcpp_fraq_align, 6},
    {"_fraq_rcpp_fraq_wait", (DL_FUNC) &_fraq_rcpp_fraq_wait, 4},
    {"_fraq_rcpp_fraq_mem_list", (DL_FUNC) &_fraq_rcpp_fraq_mem_list, 0},
    {"_fraq_rcpp_fraq_mem_remove", (DL_FUNC) &_fraq_rcpp_fraq_mem_remove, 1},
    {"_fraq_fraq_fifo_supported", (DL_FUNC) &_fraq_fraq_fifo_supported, 0},
    {NULL, NULL, 0}
};

void fraq_export_functions(DllInfo* dll);
RcppExport void R_init_fraq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    fraq_export_functions(dll);
}
