# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_fraq_options <- function(option, value, set) {
    .Call(`_fraq_rcpp_fraq_options`, option, value, set)
}

rcpp_fraq_downsample <- function(input, output, amount, nthreads = 1L) {
    invisible(.Call(`_fraq_rcpp_fraq_downsample`, input, output, amount, nthreads))
}

rcpp_fraq_slice <- function(input, output, limit, select, nthreads = 1L) {
    invisible(.Call(`_fraq_rcpp_fraq_slice`, input, output, limit, select, nthreads))
}

rcpp_fraq_convert <- function(input, output, nthreads = 1L) {
    invisible(.Call(`_fraq_rcpp_fraq_convert`, input, output, nthreads))
}

rcpp_fraq_chunk <- function(input, output_prefix, output_suffix, chunk_size, nthreads = 1L) {
    invisible(.Call(`_fraq_rcpp_fraq_chunk`, input, output_prefix, output_suffix, chunk_size, nthreads))
}

rcpp_fraq_concat <- function(input, output, nthreads = 1L) {
    invisible(.Call(`_fraq_rcpp_fraq_concat`, input, output, nthreads))
}

rcpp_fraq_count_barcodes <- function(input, barcodes, max_distance = 1L, allow_revcomp = FALSE, nthreads = 1L) {
    .Call(`_fraq_rcpp_fraq_count_barcodes`, input, barcodes, max_distance, allow_revcomp, nthreads)
}

rcpp_fraq_demux <- function(input, output_format, barcodes, max_distance = 1L, nthreads = 1L) {
    invisible(.Call(`_fraq_rcpp_fraq_demux`, input, output_format, barcodes, max_distance, nthreads))
}

rcpp_fraq_quality_filter <- function(input, output, min_mean_quality, max_low_q_bases, low_q_threshold, nthreads = 1L) {
    invisible(.Call(`_fraq_rcpp_fraq_quality_filter`, input, output, min_mean_quality, max_low_q_bases, low_q_threshold, nthreads))
}

rcpp_fraq_merge_pairs <- function(input, output_merged, output_unmerged, min_overlap = 12L, max_mismatch_rate = 0.10, consensus_mode = "max", trim_overhang = TRUE, revcomp_R2 = TRUE, nthreads = 1L) {
    .Call(`_fraq_rcpp_fraq_merge_pairs`, input, output_merged, output_unmerged, min_overlap, max_mismatch_rate, consensus_mode, trim_overhang, revcomp_R2, nthreads)
}

rcpp_fraq_trim_adapters <- function(input, output, adapters, max_distance = 1L, filter_untrimmed = TRUE, nthreads = 1L) {
    .Call(`_fraq_rcpp_fraq_trim_adapters`, input, output, adapters, max_distance, filter_untrimmed, nthreads)
}

rcpp_fraq_summary <- function(input, phred33 = TRUE, min_overlap = 12L, max_mismatch_rate = 0.10, limit = 0L, nthreads = 1L) {
    .Call(`_fraq_rcpp_fraq_summary`, input, phred33, min_overlap, max_mismatch_rate, limit, nthreads)
}

rcpp_fraq_align <- function(query, target, max_distance = 2147483647L, ambiguity_base = "", boundary = "contains", distance_metric = "lv") {
    .Call(`_fraq_rcpp_fraq_align`, query, target, max_distance, ambiguity_base, boundary, distance_metric)
}

rcpp_fraq_mem_list <- function() {
    .Call(`_fraq_rcpp_fraq_mem_list`)
}

rcpp_fraq_mem_remove <- function(mem_key) {
    .Call(`_fraq_rcpp_fraq_mem_remove`, mem_key)
}

fraq_fifo_supported <- function() {
    .Call(`_fraq_fraq_fifo_supported`)
}

